### PR TITLE
Add support for inline image data urls.

### PR DESCRIPTION
**Pull request by f0urfingeredfish**
This adds support for inline image data URIs. Same functionality as in compass.

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks! But to keep in line with the Compass function, its definition should be 
```
inline-image($image, $mime-type)
```

So `$only_path` is not applicable in this case.

**Comment by f0urfingeredfish** [comment]
@koenpunt I changed it to work like the Compass function.

**Comment by koenpunt** [comment]
Great, now if you can add a test for this, then I'll be happy to merge!

**Comment by koenpunt** [comment]
Oh but what if the image doesn't exist?

**Comment by f0urfingeredfish** [comment]
I can write a test. You didn't have tests 2 weeks ago  😉
The compiler throws an error if the file can't be found.

```
>> error in C function inline-image: ENOENT, no such file or directory '/Users/nick/work/media/images/this/doesnt/exist.gif'
>>
>> Backtrace:
>> 	sass/components/_marketplace.sass:45, in function `inline-image`
>> 	sass/components/_marketplace.sass:45
>>   Line 45  Column 14  sass/components/_marketplace.sass
```

Is there a better way to handle that error?

**Comment by koenpunt** [comment]
Maybe just return the resolved path to the file, it could be that a file is only available on a live environment.

**Comment by koenpunt** [comment]
So using `readFile` instead of `readFileSync` is probably easier to handle the error

**Comment by koenpunt** [comment]
It also might be a good idea to move the functionality of creating the data url in a function of the `Processor` object, instead of in the body of the sass function itself

**Comment by koenpunt** [comment]
>  You wouldn't get any feedback and you would assume that the image was inlined if you didn't check the generated css. 

Is it possible that we emit a warning to the sass compiler? 

> Maybe you will need it for other things ( fonts ) ?

Exactly, that's what I was thinking

**Comment by koenpunt** [comment]
Merged as 463d812c488e84455fe98298ea83273397e42101

**Pull request closed without merging**
